/*
 * CS API
 *
 * This is a simple API
 *
 * API version: 1.0.0
 * Contact: you@your-company.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Player struct {

	Id int64 `json:"id,omitempty"`

	NickName string `json:"nick_name,omitempty"`

	FirstName string `json:"first_name,omitempty"`

	LastName string `json:"last_name,omitempty"`

	Country string `json:"country,omitempty"`

	Game *Game `json:"game,omitempty"`

	Active bool `json:"active,omitempty"`
}
