/*
 * CS API
 *
 * This is a simple API
 *
 * API version: 1.0.0
 * Contact: you@your-company.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type Team struct {
	Id int64 `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	ShortName string `json:"short_name,omitempty"`

	Game *Game `json:"game,omitempty"`

	CriacaoDate time.Time `json:"criacaoDate,omitempty"`

	Active bool `json:"active,omitempty"`
}
